#! usr/bin/python3
# password_locker - a password locker program
import sys, pyperclip
password = {'email':'saiakash@4', 'office_pc':'novaone@001', 'personal_pc':'inf944@4'}

if len(sys.argv) < 2:
    print('Usage: python pw.py [account] - copy account password')
    sys.exit()
account = sys.argv[1]

if account in password.keys():
    print(password[account])
    pyperclip.copy(password[account])
else:
    print("There is no account name")

import pyperclip

text = pyperclip.paste()
lines = text.split('\n')
for i in range(len(lines)):
    lines[i] = '*' + str(lines[i])

text = '\n'.join(lines)

pyperclip.copy(text)

print('Remember, remember, the fifth of November.'.split())
print('-'.join('There can be only one.'.split()))

